name: PR Preview 2 Build

on:
  pull_request:
    branches:
      - pr-preview-2-poc
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: read

jobs:
  preview:
    uses: simoneonofri/pr-preview-2/.github/workflows/build.yml@main
    with:
      toolchain: bikeshed
      source: index.bs
